# Generated by Django 3.0.8 on 2020-07-14 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('favorite_by', models.ManyToManyField(related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
